Added solutions for module 5 tasks
js-tasks-ru/nodejs-20210618_vladyslavkhrystych pull request #4
Opened 2021-07-07 08:43 UTC by vkhrystych

2021-07-07 08:44 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-09 15:23 UTC, tadjik1 commented on 05-http-server-streams/01-file-server-get/server.js
> +  fileStream.on('data', (chunk) => {
хотя и логически все верно, но лучше сделать через .pipe(), я в видео по стримам как раз этот момент разбирал подробнее

2021-07-09 15:25 UTC, tadjik1 requested changes
в целом очень хорошие решения, лишь небольшие замечания:
про .pipe написал отдельно, а еще одно касается использования синхронных метода unlinkSync - его лучше не использовать при обработке запроса, т.к. весь поток nodejs блокируется, и другие запросы встанут в очередь. если операция по каким-то причинам будет выполняться долго - это очень негативно скажется на производительности приложения

2021-07-10 11:02 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-10 11:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-07-11 19:18 UTC, vkhrystych commented on 05-http-server-streams/01-file-server-get/server.js
> +  fileStream.on('data', (chunk) => {
Поправил, спасибо!

2021-07-11 19:19 UTC, vkhrystych commented on 05-http-server-streams/01-file-server-get/server.js
> +  fileStream.on('data', (chunk) => {
Так же избавился от unlinkSync, буду иметь в виду в будущем :)

2021-07-12 10:03 UTC, tadjik1 approved these changes
👍

2021-07-12 10:03 UTC, merged